"""
News Source Registry - Free, reliable RSS/JSON sources.

All sources are publicly accessible and do not require API keys.
"""

from __future__ import annotations

from typing import Any

DEFAULT_NEWS_SOURCES: list[dict[str, Any]] = [
    # ===== TIER 0 - REALTIME FINANCIAL (60s / 120s) =====
    {
        "name": "yahoo_finance",
        "display_name": "Yahoo Finance",
        "url": "https://feeds.finance.yahoo.com/rss/2.0/headline?s={symbol}&region=US&lang=en-US",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 60,
        "max_concurrent_requests": 5,
    },
    {
        "name": "stocktwits",
        "display_name": "Stocktwits",
        "url": "https://api.stocktwits.com/api/2/streams/symbol/{symbol}.json",
        "type": "JSON",
        "category": "COMPANY",
        "region": "GLOBAL",
        "interval_seconds": 60,
        "max_concurrent_requests": 5,
    },
    {
        "name": "cnbc_markets",
        "display_name": "CNBC Markets",
        "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partid=119005645&tagId=119005645&query={query}",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 60,
        "max_concurrent_requests": 3,
    },
    {
        "name": "marketwatch_top",
        "display_name": "MarketWatch Top Stories",
        "url": "https://feeds.content.dowjones.io/public/rss/mw_topstories",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 60,
        "max_concurrent_requests": 3,
    },
    {
        "name": "benzinga",
        "display_name": "Benzinga",
        "url": "https://www.benzinga.com/feed",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 60,
        "max_concurrent_requests": 3,
    },
    {
        "name": "nasdaq_rss",
        "display_name": "Nasdaq News",
        "url": "https://www.nasdaq.com/feed/rssoutbound",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 60,
        "max_concurrent_requests": 3,
    },
    # ===== TIER 1 - FAST INTERNATIONAL/ECONOMIC (120s) =====
    {
        "name": "reuters_business",
        "display_name": "Reuters Business",
        "url": "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
        "type": "RSS",
        "category": "ECONOMIC",
        "region": "GLOBAL",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    {
        "name": "reuters_world",
        "display_name": "Reuters World",
        "url": "https://www.reutersagency.com/feed/?best-topics=world&post_type=best",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    {
        "name": "google_news_world",
        "display_name": "Google News (World)",
        "url": "https://news.google.com/rss/search?q=world+news&hl=en-US&gl=US&ceid=US:en",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    {
        "name": "google_news_economy",
        "display_name": "Google News (Economy)",
        "url": "https://news.google.com/rss/search?q=economy+finance&hl=en-US&gl=US&ceid=US:en",
        "type": "RSS",
        "category": "ECONOMIC",
        "region": "GLOBAL",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    {
        "name": "google_news_politics",
        "display_name": "Google News (Politics)",
        "url": "https://news.google.com/rss/search?q=politics+government&hl=en-US&gl=US&ceid=US:en",
        "type": "RSS",
        "category": "POLITICAL",
        "region": "US",
        "interval_seconds": 300,
        "max_concurrent_requests": 3,
    },
    {
        "name": "ft_rss",
        "display_name": "Financial Times",
        "url": "https://www.ft.com/rss/home",
        "type": "RSS",
        "category": "ECONOMIC",
        "region": "GLOBAL",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    {
        "name": "wsj_rss",
        "display_name": "Wall Street Journal",
        "url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
        "type": "RSS",
        "category": "ECONOMIC",
        "region": "US",
        "interval_seconds": 120,
        "max_concurrent_requests": 3,
    },
    # ===== TIER 2 - POLITICAL/GEOPOLITICAL (300s) =====
    {
        "name": "bbc_politics",
        "display_name": "BBC Politics",
        "url": "http://feeds.bbci.co.uk/news/politics/rss.xml",
        "type": "RSS",
        "category": "POLITICAL",
        "region": "UK",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "bbc_world",
        "display_name": "BBC World",
        "url": "http://feeds.bbci.co.uk/news/world/rss.xml",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "aljazeera",
        "display_name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "npr_politics",
        "display_name": "NPR Politics",
        "url": "https://feeds.npr.org/1014/rss.xml",
        "type": "RSS",
        "category": "POLITICAL",
        "region": "US",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "ap_news_world",
        "display_name": "AP News World",
        "url": "https://apnews.com/hub/world/rss.xml",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "guardian_world",
        "display_name": "The Guardian World",
        "url": "https://www.theguardian.com/world/rss",
        "type": "RSS",
        "category": "INTERNATIONAL",
        "region": "GLOBAL",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    {
        "name": "guardian_politics",
        "display_name": "The Guardian Politics",
        "url": "https://www.theguardian.com/politics/rss",
        "type": "RSS",
        "category": "POLITICAL",
        "region": "UK",
        "interval_seconds": 300,
        "max_concurrent_requests": 2,
    },
    # ===== TIER 3 - SUPPLEMENTAL (900s / 15min) =====
    {
        "name": "sec_edgar",
        "display_name": "SEC EDGAR Filings",
        "url": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK={symbol}&type=10-K&dateb=&owner=include&count=40&output=atom",
        "type": "RSS",
        "category": "COMPANY",
        "region": "US",
        "interval_seconds": 900,
        "max_concurrent_requests": 2,
    },
    {
        "name": "reddit_wallstreetbets",
        "display_name": "Reddit WallStreetBets",
        "url": "https://www.reddit.com/r/wallstreetbets/search.json?q={query}&restrict_sr=1&sort=new&limit=20",
        "type": "JSON",
        "category": "COMPANY",
        "region": "US",
        "interval_seconds": 900,
        "max_concurrent_requests": 2,
    },
    {
        "name": "reddit_stocks",
        "display_name": "Reddit Stocks",
        "url": "https://www.reddit.com/r/stocks/search.json?q={query}&restrict_sr=1&sort=new&limit=20",
        "type": "JSON",
        "category": "COMPANY",
        "region": "US",
        "interval_seconds": 900,
        "max_concurrent_requests": 2,
    },
    {
        "name": "seeking_alpha",
        "display_name": "Seeking Alpha",
        "url": "https://seekingalpha.com/feed.xml",
        "type": "RSS",
        "category": "STOCK_MARKET",
        "region": "US",
        "interval_seconds": 900,
        "max_concurrent_requests": 2,
    },
    {
        "name": "coindesk",
        "display_name": "CoinDesk",
        "url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "type": "RSS",
        "category": "INDUSTRY",
        "region": "GLOBAL",
        "interval_seconds": 900,
        "max_concurrent_requests": 2,
    },
]
