sonar.projectKey=bedaanwaves
sonar.projectName=BedaanWaves
sonar.projectVersion=1.0.0

sonar.sources=app
sonar.tests=app/tests
sonar.python.version=3.11

sonar.sourceEncoding=UTF-8

sonar.exclusions=app/tests/**,**/__pycache__/**,**/*.pyc,**/migrations/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.security.owasp=true
sonar.security.sqli.enabled=true
sonar.security.xss.enabled=true
