"""Add SymbolData table

Revision ID: 4b109e7dff12
Revises: 20260806_fix_missing_tables
Create Date: 2026-08-14 20:04:55.741501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b109e7dff12'
down_revision: Union[str, None] = '20260806_fix_missing_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=10), nullable=False),
    sa.Column('stock_exchange', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_country_active', 'countries', ['is_active'], unique=False)
    op.create_index('idx_country_code', 'countries', ['iso_code'], unique=False)
    op.create_table('cross_source_consistency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_a_id', sa.String(length=100), nullable=False),
    sa.Column('source_b_id', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('consistency_metric', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consistency_sources', 'cross_source_consistency', ['source_a_id', 'source_b_id'], unique=False)
    op.create_index('idx_consistency_timestamp', 'cross_source_consistency', ['validation_timestamp'], unique=False)
    op.create_index(op.f('ix_cross_source_consistency_source_a_id'), 'cross_source_consistency', ['source_a_id'], unique=False)
    op.create_index(op.f('ix_cross_source_consistency_source_b_id'), 'cross_source_consistency', ['source_b_id'], unique=False)
    op.create_index(op.f('ix_cross_source_consistency_validation_timestamp'), 'cross_source_consistency', ['validation_timestamp'], unique=False)
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_change_7d', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_supply', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_market_cap', 'cryptocurrencies', ['market_cap'], unique=False)
    op.create_index('idx_crypto_market_cap_rank', 'cryptocurrencies', ['market_cap_rank'], unique=False)
    op.create_index('idx_crypto_symbol', 'cryptocurrencies', ['symbol'], unique=False)
    op.create_index(op.f('ix_cryptocurrencies_symbol'), 'cryptocurrencies', ['symbol'], unique=True)
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'rate_date', name='uix_currency_rate')
    )
    op.create_index(op.f('ix_currency_rates_rate_date'), 'currency_rates', ['rate_date'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_required', sa.Boolean(), nullable=True),
    sa.Column('auth_token', sa.String(length=500), nullable=True),
    sa.Column('data_format', sa.String(length=50), nullable=True),
    sa.Column('last_verification', sa.DateTime(), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index('idx_datasource_active', 'data_sources', ['is_active'], unique=False)
    op.create_index('idx_datasource_type', 'data_sources', ['source_type'], unique=False)
    op.create_table('industries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('etf_ticker', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_industry_active', 'industries', ['is_active'], unique=False)
    op.create_index('idx_industry_sector', 'industries', ['sector'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_indicators_as_of'), 'macro_indicators', ['as_of'], unique=False)
    op.create_index(op.f('ix_macro_indicators_indicator_code'), 'macro_indicators', ['indicator_code'], unique=False)
    op.create_table('market_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('base_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_index_active', 'market_indices', ['is_active'], unique=False)
    op.create_index('idx_index_country', 'market_indices', ['country'], unique=False)
    op.create_index('idx_index_exchange', 'market_indices', ['exchange'], unique=False)
    op.create_index(op.f('ix_market_indices_symbol'), 'market_indices', ['symbol'], unique=True)
    op.create_table('market_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'session_date', name='uix_market_session')
    )
    op.create_index(op.f('ix_market_sessions_market'), 'market_sessions', ['market'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uix_ml_model')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sectors_parent_id'), 'sectors', ['parent_id'], unique=False)
    op.create_table('source_authenticity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('authenticity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authenticity_source', 'source_authenticity', ['source_name'], unique=False)
    op.create_index('idx_authenticity_timestamp', 'source_authenticity', ['verification_timestamp'], unique=False)
    op.create_index(op.f('ix_source_authenticity_source_name'), 'source_authenticity', ['source_name'], unique=False)
    op.create_index(op.f('ix_source_authenticity_verification_timestamp'), 'source_authenticity', ['verification_timestamp'], unique=False)
    op.create_table('user_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notify_method', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_active', 'user_alerts', ['is_active'], unique=False)
    op.create_index('idx_alert_symbol', 'user_alerts', ['symbol'], unique=False)
    op.create_index('idx_alert_user', 'user_alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_alerts_user_id'), 'user_alerts', ['user_id'], unique=False)
    op.create_table('user_crypto_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('included_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exchange_source', sa.String(length=50), nullable=True),
    sa.Column('min_volume_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('min_market_cap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_calc', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_name', name='uix_user_crypto_config')
    )
    op.create_index('idx_crypto_config_user', 'user_crypto_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_crypto_configs_user_id'), 'user_crypto_configs', ['user_id'], unique=False)
    op.create_table('user_crypto_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('selected_cryptos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_cryptos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_watchlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exchange_source', sa.String(length=50), nullable=True),
    sa.Column('min_volume_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('min_market_cap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_change_filter', sa.String(length=20), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('validation_hash', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uix_user_crypto_settings')
    )
    op.create_index('idx_crypto_settings_user', 'user_crypto_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_crypto_settings_user_id'), 'user_crypto_settings', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'symbol', name='uix_user_favorite')
    )
    op.create_index('idx_favorite_category', 'user_favorites', ['category'], unique=False)
    op.create_index('idx_favorite_user', 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_market_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_indices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('included_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volume_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_cap_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_calc', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_name', name='uix_user_market_config')
    )
    op.create_index('idx_market_config_user', 'user_market_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_market_configs_user_id'), 'user_market_configs', ['user_id'], unique=False)
    op.create_table('user_market_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exchanges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('validation_hash', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uix_user_market_settings')
    )
    op.create_index('idx_market_settings_user', 'user_market_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_market_settings_user_id'), 'user_market_settings', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uix_user_pref')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('user_scoring_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('criteria_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'data_date', name='uix_user_scoring')
    )
    op.create_index('idx_scoring_user', 'user_scoring_results', ['user_id'], unique=False)
    op.create_index('idx_scoring_user_date', 'user_scoring_results', ['user_id', 'data_date'], unique=False)
    op.create_index('idx_scoring_user_rank', 'user_scoring_results', ['user_id', 'rank'], unique=False)
    op.create_index(op.f('ix_user_scoring_results_user_id'), 'user_scoring_results', ['user_id'], unique=False)
    op.create_table('validation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('validation_date', sa.DateTime(), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_source', 'validation_records', ['source_id'], unique=False)
    op.create_index('idx_validation_type', 'validation_records', ['validation_type'], unique=False)
    op.create_index(op.f('ix_validation_records_source_id'), 'validation_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_validation_records_validation_date'), 'validation_records', ['validation_date'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_user', 'watchlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_asset_detected', 'anomalies', ['asset_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_asset_id'), 'anomalies', ['asset_id'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('coefficient_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_cycle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('old_weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('new_weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('weight_change', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('adjustment_code', sa.String(length=50), nullable=False),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('performance_improvement', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('implementation_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adj_asset', 'coefficient_adjustments', ['asset_id'], unique=False)
    op.create_index('idx_adj_cycle_level', 'coefficient_adjustments', ['adjustment_cycle', 'level'], unique=False)
    op.create_index('idx_adj_feature_key', 'coefficient_adjustments', ['feature_key'], unique=False)
    op.create_index(op.f('ix_coefficient_adjustments_adjustment_cycle'), 'coefficient_adjustments', ['adjustment_cycle'], unique=False)
    op.create_index(op.f('ix_coefficient_adjustments_asset_id'), 'coefficient_adjustments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_coefficient_adjustments_level'), 'coefficient_adjustments', ['level'], unique=False)
    op.create_table('coefficient_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('coefficients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hist_asset_time', 'coefficient_history', ['asset_id', 'effective_at'], unique=False)
    op.create_index('idx_hist_effective', 'coefficient_history', ['effective_at'], unique=False)
    op.create_index('idx_hist_market', 'coefficient_history', ['market'], unique=False)
    op.create_index(op.f('ix_coefficient_history_asset_id'), 'coefficient_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_coefficient_history_effective_at'), 'coefficient_history', ['effective_at'], unique=False)
    op.create_table('corporate_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_events_asset_id'), 'corporate_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_corporate_events_event_date'), 'corporate_events', ['event_date'], unique=False)
    op.create_table('crypto_order_book',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_time', 'rank', name='uix_crypto_order_book_snap_rank')
    )
    op.create_index('idx_crypto_order_book_asset_snap', 'crypto_order_book', ['asset_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_crypto_order_book_asset_id'), 'crypto_order_book', ['asset_id'], unique=False)
    op.create_index(op.f('ix_crypto_order_book_snapshot_time'), 'crypto_order_book', ['snapshot_time'], unique=False)
    op.create_table('historical_data_import_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('import_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_batch', 'historical_data_import_log', ['import_batch_id'], unique=False)
    op.create_index('idx_import_status', 'historical_data_import_log', ['import_status'], unique=False)
    op.create_index(op.f('ix_historical_data_import_log_import_batch_id'), 'historical_data_import_log', ['import_batch_id'], unique=False)
    op.create_table('intl_order_book',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_time', 'rank', name='uix_intl_order_book_snap_rank')
    )
    op.create_index('idx_intl_order_book_asset_snap', 'intl_order_book', ['asset_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_intl_order_book_asset_id'), 'intl_order_book', ['asset_id'], unique=False)
    op.create_index(op.f('ix_intl_order_book_snapshot_time'), 'intl_order_book', ['snapshot_time'], unique=False)
    op.create_table('ir_financial_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period', 'statement_type', name='uix_ir_fin_stmt')
    )
    op.create_index(op.f('ix_ir_financial_statements_asset_id'), 'ir_financial_statements', ['asset_id'], unique=False)
    op.create_table('ir_free_float',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('free_float_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('base_volume', sa.BigInteger(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'as_of_date', name='uix_ir_free_float')
    )
    op.create_index('idx_ir_free_float_asset', 'ir_free_float', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_free_float_asset_id'), 'ir_free_float', ['asset_id'], unique=False)
    op.create_table('ir_fundamental_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('eps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=25, scale=2), nullable=True),
    sa.Column('book_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period', name='uix_ir_fund_ratio')
    )
    op.create_index(op.f('ix_ir_fundamental_ratios_asset_id'), 'ir_fundamental_ratios', ['asset_id'], unique=False)
    op.create_table('ir_major_shareholders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('shareholder_name', sa.String(length=255), nullable=False),
    sa.Column('shareholder_type', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.BigInteger(), nullable=True),
    sa.Column('share_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_count', sa.BigInteger(), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'shareholder_name', 'report_date', name='uix_ir_shareholder')
    )
    op.create_index('idx_ir_shareholder_asset', 'ir_major_shareholders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_major_shareholders_asset_id'), 'ir_major_shareholders', ['asset_id'], unique=False)
    op.create_table('ir_order_book',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_time', 'rank', name='uix_ir_order_book_snap_rank')
    )
    op.create_index('idx_ir_order_book_asset_snap', 'ir_order_book', ['asset_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_ir_order_book_asset_id'), 'ir_order_book', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_order_book_snapshot_time'), 'ir_order_book', ['snapshot_time'], unique=False)
    op.create_table('ir_retail_institutional',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('retail_buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('retail_sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('institutional_buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('institutional_sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('net_flow', sa.Numeric(precision=25, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_time', name='uix_ir_retail_inst')
    )
    op.create_index('idx_ir_retail_inst_asset', 'ir_retail_institutional', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_retail_institutional_asset_id'), 'ir_retail_institutional', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_retail_institutional_snapshot_time'), 'ir_retail_institutional', ['snapshot_time'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ml_pred_asset_target', 'ml_predictions', ['asset_id', 'target_date'], unique=False)
    op.create_index(op.f('ix_ml_predictions_as_of'), 'ml_predictions', ['as_of'], unique=False)
    op.create_index(op.f('ix_ml_predictions_asset_id'), 'ml_predictions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_model_id'), 'ml_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_target_date'), 'ml_predictions', ['target_date'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_published', 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_asset_id'), 'news', ['asset_id'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('raw_performance_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sub_dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aspect_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sub_aspect_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_return', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_volatility', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('target_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('target_price_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('target_volume_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('target_bitcoin_correlation', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('target_market_sentiment', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True, comment='RAW, VALIDATED, CLEANED, EXCLUDED'),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'captured_at', 'market', deferrable='True', name='uix_raw_perf_unique')
    )
    op.create_index('idx_raw_perf_asset_time', 'raw_performance_scores', ['asset_id', 'captured_at'], unique=False)
    op.create_index('idx_raw_perf_captured', 'raw_performance_scores', ['captured_at'], unique=False)
    op.create_index('idx_raw_perf_market', 'raw_performance_scores', ['market', 'exchange'], unique=False)
    op.create_index('idx_raw_perf_processed', 'raw_performance_scores', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_asset_id'), 'raw_performance_scores', ['asset_id'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_captured_at'), 'raw_performance_scores', ['captured_at'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_exchange'), 'raw_performance_scores', ['exchange'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_ingestion_id'), 'raw_performance_scores', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_is_processed'), 'raw_performance_scores', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_performance_scores_market'), 'raw_performance_scores', ['market'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('universe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_created_at'), 'screening_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_screening_results_user_id'), 'screening_results', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('alert_threshold_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'asset_id', name='uix_watchlist_asset')
    )
    op.create_index(op.f('ix_watchlist_items_asset_id'), 'watchlist_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('news_sentiment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_asset_id'), 'news_sentiment', ['asset_id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_created_at'), 'news_sentiment', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_sentiment_news_id'), 'news_sentiment', ['news_id'], unique=False)
    op.create_table('news_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_summaries_news_id'), 'news_summaries', ['news_id'], unique=False)
    op.create_table('processed_feature_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_data_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('feature_vector', sa.ARRAY(sa.Numeric(precision=20, scale=8)), nullable=False),
    sa.Column('dimension_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sub_dimension_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aspect_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sub_aspect_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalization_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_performance_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_data_id', 'processed_at', name='uix_processed_unique')
    )
    op.create_index('idx_proc_asset_market', 'processed_feature_data', ['asset_id', 'market'], unique=False)
    op.create_index('idx_proc_feature_vector', 'processed_feature_data', ['feature_vector'], unique=False)
    op.create_index('idx_proc_processed_at', 'processed_feature_data', ['processed_at'], unique=False)
    op.create_index('idx_proc_valid', 'processed_feature_data', ['is_valid'], unique=False)
    op.create_index(op.f('ix_processed_feature_data_is_valid'), 'processed_feature_data', ['is_valid'], unique=False)
    op.create_index(op.f('ix_processed_feature_data_market'), 'processed_feature_data', ['market'], unique=False)
    op.create_index(op.f('ix_processed_feature_data_processed_at'), 'processed_feature_data', ['processed_at'], unique=False)
    op.drop_index('idx_price_asset_timestamp', table_name='price_candles')
    op.drop_index('idx_price_candles_asset_timeframe_ts', table_name='price_candles')
    op.drop_index('idx_price_timeframe', table_name='price_candles')
    op.drop_index('ix_price_candles_asset_id', table_name='price_candles')
    op.drop_index('ix_price_candles_timestamp', table_name='price_candles')
    op.drop_table('price_candles')
    op.drop_column('api_logs', 'updated_by')
    op.create_index(op.f('ix_crypto_ml_signals_asset_id'), 'crypto_ml_signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_crypto_ml_signals_is_active'), 'crypto_ml_signals', ['is_active'], unique=False)
    op.create_index(op.f('ix_crypto_ml_signals_model_version'), 'crypto_ml_signals', ['model_version'], unique=False)
    op.create_index(op.f('ix_crypto_ml_signals_signal_type'), 'crypto_ml_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_crypto_ml_signals_snapshot_id'), 'crypto_ml_signals', ['snapshot_id'], unique=False)
    op.add_column('crypto_price_candles', sa.Column('adjusted_close', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('crypto_price_candles', sa.Column('split_ratio', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('crypto_price_candles', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('crypto_price_candles', sa.Column('data_quality', sa.String(length=10), nullable=True))
    op.add_column('crypto_price_candles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('crypto_price_candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('crypto_price_candles', 'volume',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('crypto_price_candles', 'turnover',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=True)
    op.create_index('idx_crypto_price_candles_asset_ts', 'crypto_price_candles', ['asset_id', 'timestamp'], unique=False)
    op.create_index('idx_crypto_price_candles_tf_ts', 'crypto_price_candles', ['timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_crypto_price_candles_asset_id'), 'crypto_price_candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_crypto_price_candles_timestamp'), 'crypto_price_candles', ['timestamp'], unique=False)
    op.create_unique_constraint('uix_crypto_price_candles_asset_ts_tf', 'crypto_price_candles', ['asset_id', 'timestamp', 'timeframe'])
    op.add_column('intl_price_candles', sa.Column('adjusted_close', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('intl_price_candles', sa.Column('split_ratio', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('intl_price_candles', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('intl_price_candles', sa.Column('data_quality', sa.String(length=10), nullable=True))
    op.add_column('intl_price_candles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('intl_price_candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('intl_price_candles', 'volume',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('intl_price_candles', 'turnover',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=True)
    op.create_index('idx_intl_price_candles_asset_ts', 'intl_price_candles', ['asset_id', 'timestamp'], unique=False)
    op.create_index('idx_intl_price_candles_tf_ts', 'intl_price_candles', ['timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_intl_price_candles_asset_id'), 'intl_price_candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_intl_price_candles_timestamp'), 'intl_price_candles', ['timestamp'], unique=False)
    op.create_unique_constraint('uix_intl_price_candles_asset_ts_tf', 'intl_price_candles', ['asset_id', 'timestamp', 'timeframe'])
    op.add_column('ir_price_candles', sa.Column('adjusted_close', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('ir_price_candles', sa.Column('split_ratio', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('ir_price_candles', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('ir_price_candles', sa.Column('data_quality', sa.String(length=10), nullable=True))
    op.add_column('ir_price_candles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('ir_price_candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('ir_price_candles', 'volume',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('ir_price_candles', 'turnover',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=True)
    op.create_index('idx_ir_price_candles_asset_ts', 'ir_price_candles', ['asset_id', 'timestamp'], unique=False)
    op.create_index('idx_ir_price_candles_tf_ts', 'ir_price_candles', ['timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ir_price_candles_asset_id'), 'ir_price_candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ir_price_candles_timestamp'), 'ir_price_candles', ['timestamp'], unique=False)
    op.create_unique_constraint('uix_ir_price_candles_asset_ts_tf', 'ir_price_candles', ['asset_id', 'timestamp', 'timeframe'])
    op.add_column('market_data_snapshots', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_market_data_snapshots_asset_id'), 'market_data_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_interval'), 'market_data_snapshots', ['interval'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_is_fresh'), 'market_data_snapshots', ['is_fresh'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_snapshot_time'), 'market_data_snapshots', ['snapshot_time'], unique=False)
    op.add_column('raw_market_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_raw_market_data_asset_id'), 'raw_market_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_raw_market_data_data_type'), 'raw_market_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_raw_market_data_market'), 'raw_market_data', ['market'], unique=False)
    op.create_index(op.f('ix_raw_market_data_raw_symbol'), 'raw_market_data', ['raw_symbol'], unique=False)
    op.create_index(op.f('ix_raw_market_data_source_timestamp'), 'raw_market_data', ['source_timestamp'], unique=False)
    op.alter_column('symbol_data', 'country_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'US'::bpchar"))
    op.alter_column('symbol_data', 'market_category',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.drop_index('idx_symbol_data_industry', table_name='symbol_data')
    op.drop_constraint('symbol_data_symbol_key', 'symbol_data', type_='unique')
    op.create_index(op.f('ix_symbol_data_created_at'), 'symbol_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_symbol_data_symbol'), 'symbol_data', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_data_symbol'), table_name='symbol_data')
    op.drop_index(op.f('ix_symbol_data_created_at'), table_name='symbol_data')
    op.create_unique_constraint('symbol_data_symbol_key', 'symbol_data', ['symbol'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_symbol_data_industry', 'symbol_data', ['industry_code'], unique=False)
    op.alter_column('symbol_data', 'market_category',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('symbol_data', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'US'::bpchar"))
    op.drop_index(op.f('ix_raw_market_data_source_timestamp'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_raw_symbol'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_market'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_data_type'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_asset_id'), table_name='raw_market_data')
    op.drop_column('raw_market_data', 'updated_at')
    op.drop_index(op.f('ix_market_data_snapshots_snapshot_time'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_is_fresh'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_interval'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_asset_id'), table_name='market_data_snapshots')
    op.drop_column('market_data_snapshots', 'updated_at')
    op.drop_constraint('uix_ir_price_candles_asset_ts_tf', 'ir_price_candles', type_='unique')
    op.drop_index(op.f('ix_ir_price_candles_timestamp'), table_name='ir_price_candles')
    op.drop_index(op.f('ix_ir_price_candles_asset_id'), table_name='ir_price_candles')
    op.drop_index('idx_ir_price_candles_tf_ts', table_name='ir_price_candles')
    op.drop_index('idx_ir_price_candles_asset_ts', table_name='ir_price_candles')
    op.alter_column('ir_price_candles', 'turnover',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('ir_price_candles', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('ir_price_candles', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('ir_price_candles', 'created_at')
    op.drop_column('ir_price_candles', 'data_quality')
    op.drop_column('ir_price_candles', 'source')
    op.drop_column('ir_price_candles', 'split_ratio')
    op.drop_column('ir_price_candles', 'adjusted_close')
    op.drop_constraint('uix_intl_price_candles_asset_ts_tf', 'intl_price_candles', type_='unique')
    op.drop_index(op.f('ix_intl_price_candles_timestamp'), table_name='intl_price_candles')
    op.drop_index(op.f('ix_intl_price_candles_asset_id'), table_name='intl_price_candles')
    op.drop_index('idx_intl_price_candles_tf_ts', table_name='intl_price_candles')
    op.drop_index('idx_intl_price_candles_asset_ts', table_name='intl_price_candles')
    op.alter_column('intl_price_candles', 'turnover',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('intl_price_candles', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('intl_price_candles', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('intl_price_candles', 'created_at')
    op.drop_column('intl_price_candles', 'data_quality')
    op.drop_column('intl_price_candles', 'source')
    op.drop_column('intl_price_candles', 'split_ratio')
    op.drop_column('intl_price_candles', 'adjusted_close')
    op.drop_constraint('uix_crypto_price_candles_asset_ts_tf', 'crypto_price_candles', type_='unique')
    op.drop_index(op.f('ix_crypto_price_candles_timestamp'), table_name='crypto_price_candles')
    op.drop_index(op.f('ix_crypto_price_candles_asset_id'), table_name='crypto_price_candles')
    op.drop_index('idx_crypto_price_candles_tf_ts', table_name='crypto_price_candles')
    op.drop_index('idx_crypto_price_candles_asset_ts', table_name='crypto_price_candles')
    op.alter_column('crypto_price_candles', 'turnover',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('crypto_price_candles', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('crypto_price_candles', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('crypto_price_candles', 'created_at')
    op.drop_column('crypto_price_candles', 'data_quality')
    op.drop_column('crypto_price_candles', 'source')
    op.drop_column('crypto_price_candles', 'split_ratio')
    op.drop_column('crypto_price_candles', 'adjusted_close')
    op.drop_index(op.f('ix_crypto_ml_signals_snapshot_id'), table_name='crypto_ml_signals')
    op.drop_index(op.f('ix_crypto_ml_signals_signal_type'), table_name='crypto_ml_signals')
    op.drop_index(op.f('ix_crypto_ml_signals_model_version'), table_name='crypto_ml_signals')
    op.drop_index(op.f('ix_crypto_ml_signals_is_active'), table_name='crypto_ml_signals')
    op.drop_index(op.f('ix_crypto_ml_signals_asset_id'), table_name='crypto_ml_signals')
    op.add_column('api_logs', sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('price_candles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('turnover', sa.NUMERIC(precision=25, scale=2), autoincrement=False, nullable=True),
    sa.Column('transactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('split_ratio', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('data_quality', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('high >= low', name='chk_legacy_candle_high'),
    sa.CheckConstraint('high >= open AND high >= close', name='chk_high_values'),
    sa.CheckConstraint('low <= open AND low <= close', name='chk_low_values'),
    sa.CheckConstraint('volume >= 0', name='chk_legacy_candle_volume'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='price_candles_asset_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_candles_pkey'),
    sa.UniqueConstraint('asset_id', 'timestamp', 'timeframe', name='uix_price_asset_timestamp', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_price_candles_timestamp', 'price_candles', ['timestamp'], unique=False)
    op.create_index('ix_price_candles_asset_id', 'price_candles', ['asset_id'], unique=False)
    op.create_index('idx_price_timeframe', 'price_candles', ['timeframe', 'timestamp'], unique=False)
    op.create_index('idx_price_candles_asset_timeframe_ts', 'price_candles', ['asset_id', 'timeframe', 'timestamp'], unique=False)
    op.create_index('idx_price_asset_timestamp', 'price_candles', ['asset_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_processed_feature_data_processed_at'), table_name='processed_feature_data')
    op.drop_index(op.f('ix_processed_feature_data_market'), table_name='processed_feature_data')
    op.drop_index(op.f('ix_processed_feature_data_is_valid'), table_name='processed_feature_data')
    op.drop_index('idx_proc_valid', table_name='processed_feature_data')
    op.drop_index('idx_proc_processed_at', table_name='processed_feature_data')
    op.drop_index('idx_proc_feature_vector', table_name='processed_feature_data')
    op.drop_index('idx_proc_asset_market', table_name='processed_feature_data')
    op.drop_table('processed_feature_data')
    op.drop_index(op.f('ix_news_summaries_news_id'), table_name='news_summaries')
    op.drop_table('news_summaries')
    op.drop_index(op.f('ix_news_sentiment_news_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_created_at'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_asset_id'), table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_asset_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_screening_results_user_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_created_at'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_raw_performance_scores_market'), table_name='raw_performance_scores')
    op.drop_index(op.f('ix_raw_performance_scores_is_processed'), table_name='raw_performance_scores')
    op.drop_index(op.f('ix_raw_performance_scores_ingestion_id'), table_name='raw_performance_scores')
    op.drop_index(op.f('ix_raw_performance_scores_exchange'), table_name='raw_performance_scores')
    op.drop_index(op.f('ix_raw_performance_scores_captured_at'), table_name='raw_performance_scores')
    op.drop_index(op.f('ix_raw_performance_scores_asset_id'), table_name='raw_performance_scores')
    op.drop_index('idx_raw_perf_processed', table_name='raw_performance_scores')
    op.drop_index('idx_raw_perf_market', table_name='raw_performance_scores')
    op.drop_index('idx_raw_perf_captured', table_name='raw_performance_scores')
    op.drop_index('idx_raw_perf_asset_time', table_name='raw_performance_scores')
    op.drop_table('raw_performance_scores')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_asset_id'), table_name='news')
    op.drop_index('idx_news_published', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_ml_predictions_target_date'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_model_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_asset_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_as_of'), table_name='ml_predictions')
    op.drop_index('idx_ml_pred_asset_target', table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_ir_retail_institutional_snapshot_time'), table_name='ir_retail_institutional')
    op.drop_index(op.f('ix_ir_retail_institutional_asset_id'), table_name='ir_retail_institutional')
    op.drop_index('idx_ir_retail_inst_asset', table_name='ir_retail_institutional')
    op.drop_table('ir_retail_institutional')
    op.drop_index(op.f('ix_ir_order_book_snapshot_time'), table_name='ir_order_book')
    op.drop_index(op.f('ix_ir_order_book_asset_id'), table_name='ir_order_book')
    op.drop_index('idx_ir_order_book_asset_snap', table_name='ir_order_book')
    op.drop_table('ir_order_book')
    op.drop_index(op.f('ix_ir_major_shareholders_asset_id'), table_name='ir_major_shareholders')
    op.drop_index('idx_ir_shareholder_asset', table_name='ir_major_shareholders')
    op.drop_table('ir_major_shareholders')
    op.drop_index(op.f('ix_ir_fundamental_ratios_asset_id'), table_name='ir_fundamental_ratios')
    op.drop_table('ir_fundamental_ratios')
    op.drop_index(op.f('ix_ir_free_float_asset_id'), table_name='ir_free_float')
    op.drop_index('idx_ir_free_float_asset', table_name='ir_free_float')
    op.drop_table('ir_free_float')
    op.drop_index(op.f('ix_ir_financial_statements_asset_id'), table_name='ir_financial_statements')
    op.drop_table('ir_financial_statements')
    op.drop_index(op.f('ix_intl_order_book_snapshot_time'), table_name='intl_order_book')
    op.drop_index(op.f('ix_intl_order_book_asset_id'), table_name='intl_order_book')
    op.drop_index('idx_intl_order_book_asset_snap', table_name='intl_order_book')
    op.drop_table('intl_order_book')
    op.drop_index(op.f('ix_historical_data_import_log_import_batch_id'), table_name='historical_data_import_log')
    op.drop_index('idx_import_status', table_name='historical_data_import_log')
    op.drop_index('idx_import_batch', table_name='historical_data_import_log')
    op.drop_table('historical_data_import_log')
    op.drop_index(op.f('ix_crypto_order_book_snapshot_time'), table_name='crypto_order_book')
    op.drop_index(op.f('ix_crypto_order_book_asset_id'), table_name='crypto_order_book')
    op.drop_index('idx_crypto_order_book_asset_snap', table_name='crypto_order_book')
    op.drop_table('crypto_order_book')
    op.drop_index(op.f('ix_corporate_events_event_date'), table_name='corporate_events')
    op.drop_index(op.f('ix_corporate_events_asset_id'), table_name='corporate_events')
    op.drop_table('corporate_events')
    op.drop_index(op.f('ix_coefficient_history_effective_at'), table_name='coefficient_history')
    op.drop_index(op.f('ix_coefficient_history_asset_id'), table_name='coefficient_history')
    op.drop_index('idx_hist_market', table_name='coefficient_history')
    op.drop_index('idx_hist_effective', table_name='coefficient_history')
    op.drop_index('idx_hist_asset_time', table_name='coefficient_history')
    op.drop_table('coefficient_history')
    op.drop_index(op.f('ix_coefficient_adjustments_level'), table_name='coefficient_adjustments')
    op.drop_index(op.f('ix_coefficient_adjustments_asset_id'), table_name='coefficient_adjustments')
    op.drop_index(op.f('ix_coefficient_adjustments_adjustment_cycle'), table_name='coefficient_adjustments')
    op.drop_index('idx_adj_feature_key', table_name='coefficient_adjustments')
    op.drop_index('idx_adj_cycle_level', table_name='coefficient_adjustments')
    op.drop_index('idx_adj_asset', table_name='coefficient_adjustments')
    op.drop_table('coefficient_adjustments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_asset_id'), table_name='anomalies')
    op.drop_index('idx_anomaly_asset_detected', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index('idx_watchlist_user', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_validation_records_validation_date'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_source_id'), table_name='validation_records')
    op.drop_index('idx_validation_type', table_name='validation_records')
    op.drop_index('idx_validation_source', table_name='validation_records')
    op.drop_table('validation_records')
    op.drop_index(op.f('ix_user_scoring_results_user_id'), table_name='user_scoring_results')
    op.drop_index('idx_scoring_user_rank', table_name='user_scoring_results')
    op.drop_index('idx_scoring_user_date', table_name='user_scoring_results')
    op.drop_index('idx_scoring_user', table_name='user_scoring_results')
    op.drop_table('user_scoring_results')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_market_settings_user_id'), table_name='user_market_settings')
    op.drop_index('idx_market_settings_user', table_name='user_market_settings')
    op.drop_table('user_market_settings')
    op.drop_index(op.f('ix_user_market_configs_user_id'), table_name='user_market_configs')
    op.drop_index('idx_market_config_user', table_name='user_market_configs')
    op.drop_table('user_market_configs')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index('idx_favorite_user', table_name='user_favorites')
    op.drop_index('idx_favorite_category', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_user_crypto_settings_user_id'), table_name='user_crypto_settings')
    op.drop_index('idx_crypto_settings_user', table_name='user_crypto_settings')
    op.drop_table('user_crypto_settings')
    op.drop_index(op.f('ix_user_crypto_configs_user_id'), table_name='user_crypto_configs')
    op.drop_index('idx_crypto_config_user', table_name='user_crypto_configs')
    op.drop_table('user_crypto_configs')
    op.drop_index(op.f('ix_user_alerts_user_id'), table_name='user_alerts')
    op.drop_index('idx_alert_user', table_name='user_alerts')
    op.drop_index('idx_alert_symbol', table_name='user_alerts')
    op.drop_index('idx_alert_active', table_name='user_alerts')
    op.drop_table('user_alerts')
    op.drop_index(op.f('ix_source_authenticity_verification_timestamp'), table_name='source_authenticity')
    op.drop_index(op.f('ix_source_authenticity_source_name'), table_name='source_authenticity')
    op.drop_index('idx_authenticity_timestamp', table_name='source_authenticity')
    op.drop_index('idx_authenticity_source', table_name='source_authenticity')
    op.drop_table('source_authenticity')
    op.drop_index(op.f('ix_sectors_parent_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_market_sessions_market'), table_name='market_sessions')
    op.drop_table('market_sessions')
    op.drop_index(op.f('ix_market_indices_symbol'), table_name='market_indices')
    op.drop_index('idx_index_exchange', table_name='market_indices')
    op.drop_index('idx_index_country', table_name='market_indices')
    op.drop_index('idx_index_active', table_name='market_indices')
    op.drop_table('market_indices')
    op.drop_index(op.f('ix_macro_indicators_indicator_code'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_as_of'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index('idx_industry_sector', table_name='industries')
    op.drop_index('idx_industry_active', table_name='industries')
    op.drop_table('industries')
    op.drop_index('idx_datasource_type', table_name='data_sources')
    op.drop_index('idx_datasource_active', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_currency_rates_rate_date'), table_name='currency_rates')
    op.drop_table('currency_rates')
    op.drop_index(op.f('ix_cryptocurrencies_symbol'), table_name='cryptocurrencies')
    op.drop_index('idx_crypto_symbol', table_name='cryptocurrencies')
    op.drop_index('idx_crypto_market_cap_rank', table_name='cryptocurrencies')
    op.drop_index('idx_crypto_market_cap', table_name='cryptocurrencies')
    op.drop_table('cryptocurrencies')
    op.drop_index(op.f('ix_cross_source_consistency_validation_timestamp'), table_name='cross_source_consistency')
    op.drop_index(op.f('ix_cross_source_consistency_source_b_id'), table_name='cross_source_consistency')
    op.drop_index(op.f('ix_cross_source_consistency_source_a_id'), table_name='cross_source_consistency')
    op.drop_index('idx_consistency_timestamp', table_name='cross_source_consistency')
    op.drop_index('idx_consistency_sources', table_name='cross_source_consistency')
    op.drop_table('cross_source_consistency')
    op.drop_index('idx_country_code', table_name='countries')
    op.drop_index('idx_country_active', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
