"""Initial migration with all models

Revision ID: c57c8b5674de
Revises: 
Create Date: 2026-07-09 20:43:13.219558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57c8b5674de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_endpoint', 'api_logs', ['endpoint'], unique=False)
    op.create_index('idx_log_timestamp', 'api_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_created_at'), 'api_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_endpoint'), 'api_logs', ['endpoint'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('isin_code', sa.String(length=12), nullable=True),
    sa.Column('cusip_code', sa.String(length=9), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('delisting_date', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_active_market', 'assets', ['active', 'market'], unique=False)
    op.create_index('idx_asset_sector', 'assets', ['sector'], unique=False)
    op.create_index(op.f('ix_assets_active'), 'assets', ['active'], unique=False)
    op.create_index(op.f('ix_assets_asset_class'), 'assets', ['asset_class'], unique=False)
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_market'), 'assets', ['market'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portfolio_type', sa.String(length=20), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=True),
    sa.Column('target_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('public_token', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uix_portfolio_user_name')
    )
    op.create_index('idx_portfolio_user', 'portfolios', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('threshold_direction', sa.String(length=10), nullable=True),
    sa.Column('notification_channel', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('ml_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_return', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('expected_volatility', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('technical_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fundamental_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('actual_return', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_active_generated', 'ml_signals', ['is_active', 'generated_at'], unique=False)
    op.create_index('idx_signal_model', 'ml_signals', ['ml_model_version'], unique=False)
    op.create_index(op.f('ix_ml_signals_asset_id'), 'ml_signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ml_signals_is_active'), 'ml_signals', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_signals_ml_model_version'), 'ml_signals', ['ml_model_version'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=25, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=25, scale=2), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_positive_quantity'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uix_portfolio_asset')
    )
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('price_candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=25, scale=2), nullable=True),
    sa.Column('transactions', sa.Integer(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('split_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('data_quality', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('high >= open AND high >= close', name='chk_high_values'),
    sa.CheckConstraint('low <= open AND low <= close', name='chk_low_values'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timestamp', 'timeframe', name='uix_price_asset_timestamp')
    )
    op.create_index('idx_price_asset_timestamp', 'price_candles', ['asset_id', 'timestamp'], unique=False)
    op.create_index('idx_price_timeframe', 'price_candles', ['timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_candles_asset_id'), 'price_candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_candles_timestamp'), 'price_candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_candles_timestamp'), table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_asset_id'), table_name='price_candles')
    op.drop_index('idx_price_timeframe', table_name='price_candles')
    op.drop_index('idx_price_asset_timestamp', table_name='price_candles')
    op.drop_table('price_candles')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_ml_signals_ml_model_version'), table_name='ml_signals')
    op.drop_index(op.f('ix_ml_signals_is_active'), table_name='ml_signals')
    op.drop_index(op.f('ix_ml_signals_asset_id'), table_name='ml_signals')
    op.drop_index('idx_signal_model', table_name='ml_signals')
    op.drop_index('idx_signal_active_generated', table_name='ml_signals')
    op.drop_table('ml_signals')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index('idx_portfolio_user', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_market'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_class'), table_name='assets')
    op.drop_index(op.f('ix_assets_active'), table_name='assets')
    op.drop_index('idx_asset_sector', table_name='assets')
    op.drop_index('idx_asset_active_market', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_api_logs_endpoint'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_created_at'), table_name='api_logs')
    op.drop_index('idx_log_timestamp', table_name='api_logs')
    op.drop_index('idx_log_endpoint', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
